syntax = "proto3";

package auth;

import "google/protobuf/descriptor.proto";

option go_package = "github.com/Wolkodaf/protos/gen/go/auth;auth";

service Auth {
    rpc Register(RegisterRequest) returns (RegisterResponse);
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc GetNewTokens(TokensRequest) returns (TokenResponse);

    // Профиль пользователя и Аватарка
    rpc GetProfile(GetProfileRequest) returns (GetProfileResponse);
    rpc GetAvatar(GetAvatarRequest) returns (GetAvatarResponse);
    rpc GenerateAvatarUploadUrl(GenerateAvatarUploadUrlRequest) returns (GenerateAvatarUploadUrlResponse);

    // Админские ручки
    rpc ListPendingUsers(ListPendingUsersRequest) returns (ListPendingUsersResponse);
    rpc AssignRole(AssignRoleRequest) returns (AssignRoleResponse);

    // 
}

// --- AUTH MESSAGES ---
message RegisterRequest {
    string username = 1;
    string email = 2;
    string password = 3 [debug_redact = true];
}

message RegisterResponse {
    int64 user_id = 1;
}

message LoginRequest {
    string email = 1;
    string password = 2 [debug_redact = true];
}

message LoginResponse {
    string access_token = 1;
    string refresh_token = 2;
}

message TokensRequest {
    string refresh_token = 1;
}

message TokenResponse {
    string access_token = 1;
    string refresh_token = 2;
}

message GetProfileRequest {
    int64 user_id = 1;
}

message GetProfileResponse {
    int64 user_id = 1;
    string username = 2;
    string email = 3;
    string user_role = 4;
    string avatar_url = 5; // Presigned GET ссылка на аватарку
}

message GetAvatarRequest {
    int64 user_id = 1;
}

message GetAvatarResponse {
    string avatar_url = 1;
}

message GenerateAvatarUploadUrlRequest {
    int64 user_id = 1;
    string content_type = 2; // e.g. "image/png", "image/jpeg"
}

message GenerateAvatarUploadUrlResponse {
    string upload_url = 1;  // Presigned PUT ссылка для загрузки в S3
    string avatar_key = 2;  // Ключ файла в S3
}

// --- ADMIN MESSAGES ---
message ListPendingUsersRequest {
    // пагинация
    int32 limit = 1;
    int32 offset = 2;
}

message PendingUser {
    int64 user_id = 1;
    string username = 2;
    string email = 3;
    string created_at = 4;
}

message ListPendingUsersResponse {
    repeated PendingUser users = 1;
    int32 total_count = 2; // кол-во страниц
}

message AssignRoleRequest {
    int64 target_user_id = 1; // Кому выдаем
    string new_role = 2;    // Какую роль выдаем
}

message AssignRoleResponse {
    bool success = 1;
}