syntax = "proto3";

package template;

option go_package = "github.com/Wolkodaf/protos/gen/go/templates;templates";

service Temp {
  rpc UploadAndParse (stream UploadRequest) returns (UploadResponse);
  rpc CheckStatus (StatusRequest) returns (StatusResponse);

  rpc CreateTemplateParams (CreateParamsRequest) returns (CreateParamsResponse);
}

message UploadRequest {
  oneof data {
    FileInfo info = 1; // Метаданные (имя файла, тип)
    bytes chunk_data = 2; // Кусочки файла
  }
}

message FileInfo {
  string filename = 1;
  string content_type = 2;
}

message UploadResponse {
  string task_id = 1; // ID, по которому будем проверять статус
}

message StatusRequest {
  string task_id = 1;
}

message StatusResponse {
  string status = 1;  // "pending", "processing", "done", "error"
  repeated string names = 2;
  string error_message = 3;
}

message CreateParamsRequest {
  string task_id = 1;
  map<string, string> params = 2; 
}

message CreateParamsResponse {
  string template_id = 1;
  string error = 2;
}